In [52]:
import pandas as pd
import numpy as np

In [53]:
data = pd.read_csv("dataset_1.csv")

In [54]:
data.shape

(50000, 301)

In [55]:
data.head()

var_1  var_2  var_3  var_4  var_5  var_6  var_7  var_8  var_9  var_10  ...  \
0      0      0    0.0   0.00    0.0      0      0      0      0       0  ...   
1      0      0    0.0   3.00    0.0      0      0      0      0       0  ...   
2      0      0    0.0   5.88    0.0      0      0      0      0       0  ...   
3      0      0    0.0  14.10    0.0      0      0      0      0       0  ...   
4      0      0    0.0   5.76    0.0      0      0      0      0       0  ...   

   var_292  var_293  var_294  var_295  var_296  var_297  var_298  var_299  \
0      0.0        0        0        0        0        0        0      0.0   
1      0.0        0        0        0        0        0        0      0.0   
2      0.0        0        0        3        0        0        0      0.0   
3      0.0        0        0        0        0        0        0      0.0   
4      0.0        0        0        0        0        0        0      0.0   

      var_300  target  
0      0.0000       0  
1      0.0000       0  
2  67772.7216       0  
3      0.0000       0  
4      0.0000       0  

[5 rows x 301 columns]

In [56]:
feature_cols = ["var_{}".format(i) for i in range(1, 301)]

In [57]:
data.isnull().sum().values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [58]:
features = data[feature_cols]
target = data["target"]

In [59]:
np.unique([typ for typ in features.dtypes])

array([dtype('int64'), dtype('float64')], dtype=object)

All variables are numeric.

In [60]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [61]:
X_train.shape

(40000, 300)

## Remove constant features

Constant features are features that show same value for all observations.

### ~ With sklearn ~

In [62]:
from sklearn.feature_selection import VarianceThreshold

In [63]:
# With sklearn VarianceThreshold
sel = VarianceThreshold(threshold=0)
sel.fit(X_train)

VarianceThreshold(threshold=0)

In [64]:
print("features to remove: {}".format(len(feature_cols) - sum(sel.get_support())))

features to remove: 42


In [65]:
X_train.columns[~sel.get_support()]

Index(['var_14', 'var_23', 'var_33', 'var_34', 'var_44', 'var_61', 'var_66',
       'var_67', 'var_69', 'var_73', 'var_80', 'var_81', 'var_87', 'var_89',
       'var_92', 'var_97', 'var_99', 'var_112', 'var_113', 'var_120',
       'var_122', 'var_127', 'var_129', 'var_135', 'var_158', 'var_167',
       'var_171', 'var_178', 'var_180', 'var_182', 'var_183', 'var_195',
       'var_196', 'var_201', 'var_212', 'var_215', 'var_225', 'var_227',
       'var_248', 'var_287', 'var_294', 'var_297'],
      dtype='object')

In [66]:
X_train["var_14"].unique()

array([0])

In [67]:
X_train["var_23"].unique()

array([0])

Here, we can observed that the variables have only one value.

In [68]:
# Remove the constant features found
X_train = sel.transform(X_train)
X_test = sel.transform(X_test)

In [69]:
X_train.shape, X_test.shape

((40000, 258), (10000, 258))

42 constant variables have been removed from the dataset, reducing 300 features to __258 features.__

### *** With pandas ***

In [70]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [71]:
constant_features = [feat for feat in X_train.columns if X_train[feat].std() == 0]

In [72]:
X_train.drop(labels=constant_features, axis=1, inplace=True)
X_test.drop(labels=constant_features, axis=1, inplace=True)

X_train.shape, X_test.shape

/home/nicolas/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4164: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


((40000, 258), (10000, 258))

In [73]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [74]:
# Count variables with a unique value
constant_features = [feat for feat in X_train.columns if X_train[feat].nunique() == 1]

In [75]:
X_train.drop(labels=constant_features, axis=1, inplace=True)
X_test.drop(labels=constant_features, axis=1, inplace=True)

X_train.shape, X_test.shape

((40000, 258), (10000, 258))

__Note__: By default __nunique()__ ignores missing values, so in order to not ignore them use __dropna=False__.

## Remove quasi-constant

Quasi-constant features are features that exhibit the same value for the majority of observations of the dataset

In [76]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [77]:
sel = VarianceThreshold(threshold=0.01)# Variance of 0.01 threshold, 99% 
sel.fit(X_train)

VarianceThreshold(threshold=0.01)

In [78]:
print("features to remove: {}".format(len(feature_cols) - sum(sel.get_support())))

features to remove: 87


In [79]:
quasi_constant_features = [feat for feat in feature_cols if feat not in X_train.columns[sel.get_support()]]

In [80]:
quasi_constant_features[0]

'var_2'

In [81]:
# Let's observe the percentage that represents every value in the variable
X_train["var_2"].value_counts() / X_train.shape[0]

0    0.999925
1    0.000075
Name: var_2, dtype: float64

In [82]:
# we can then drop these columns from the train and test sets
X_train = sel.transform(X_train)
X_test = sel.transform(X_test)

X_train.shape, X_test.shape

((40000, 213), (10000, 213))

In [83]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [84]:
quasi_constant_features = [feat for feat in X_train.columns if X_train[feat].std() < 0.01]

In [85]:
print("features to remove: {}".format(len(quasi_constant_features)))

features to remove: 47


In [86]:
X_train.drop(labels=quasi_constant_features, axis=1, inplace=True)
X_test.drop(labels=quasi_constant_features, axis=1, inplace=True)

X_train.shape, X_test.shape

/home/nicolas/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4164: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


((40000, 253), (10000, 253))

In [87]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [88]:
%%time
quasi_constant_features = []
for feat in X_train.columns:
    # Calculate the percentage that represent each value for the variable, and take the
    # predominant one
    predominant = (X_train[feat].value_counts() / np.float(X_train.shape[0])).sort_values(ascending=False).values[0]
    
    if predominant >= 0.998:
        quasi_constant_features.append(feat)

/home/nicolas/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


CPU times: user 406 ms, sys: 445 µs, total: 407 ms
Wall time: 402 ms


In [89]:
print("features to remove: {}".format(len(quasi_constant_features)))

features to remove: 139


In [90]:
X_train.drop(labels=quasi_constant_features, axis=1, inplace=True)
X_test.drop(labels=quasi_constant_features, axis=1, inplace=True)

X_train.shape, X_test.shape

((40000, 161), (10000, 161))

## Remove Duplicates

In [91]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [92]:
# Check if both features contain the same values
X_train["var_1"].equals(X_train["var_1"])

True

In [93]:
X_train.columns

Index(['var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7', 'var_8',
       'var_9', 'var_10',
       ...
       'var_291', 'var_292', 'var_293', 'var_294', 'var_295', 'var_296',
       'var_297', 'var_298', 'var_299', 'var_300'],
      dtype='object', length=300)

In [94]:
%%time
duplicated_dict = {}
duplicated_features = []
for i, feat1 in enumerate(X_train.columns):
    # Check if the variable is in the current duplicated list, skip it
    if feat1 not in duplicated_features:
        # Take all the other variables
        all_other_feats = X_train.columns[i+1:]
        # Initialize the dictionary of duplicated features of feat1
        duplicated_dict[feat1] = []
        for feat2 in all_other_feats:
            # Check if both variables contain the same values
            if X_train[feat1].equals(X_train[feat2]):
                # Append the duplicated feature
                duplicated_features.append(feat2)
                # Append the duplicated feature to the feature dictionary
                duplicated_dict[feat1].append(feat2)

CPU times: user 2.06 s, sys: 1.78 ms, total: 2.06 s
Wall time: 2.07 s


In [95]:
print("There are {} duplicated features".format(len(duplicated_features)))

There are 56 duplicated features


Let's look on some of the duplicated features found

In [45]:
duplicated_dict["var_6"]

['var_151']

In [50]:
X_train["var_6"].unique()

array([       0, 99999999])

In [51]:
X_train["var_151"].unique()

array([       0, 99999999])

In [54]:
# Retain all the non-duplicated features (keys on the dictionary)
X_train = X_train[duplicated_dict.keys()]
X_test = X_test[duplicated_dict.keys()]

X_train.shape, X_test.shape

((40000, 244), (10000, 244))

## ** _Feature-Engine methods_ **

In [56]:
!pip install feature_engine

     |████████████████████████████████| 152 kB 408 kB/s eta 0:00:01
     |████████████████████████████████| 15.3 MB 2.5 MB/s eta 0:00:01
     |████████████████████████████████| 22.3 MB 2.5 MB/s eta 0:00:01     |███████████████████████████▊    | 19.3 MB 2.1 MB/s eta 0:00:02
     |████████████████████████████████| 27.4 MB 5.4 MB/s eta 0:00:01
     |████████████████████████████████| 9.5 MB 4.4 MB/s eta 0:00:01
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.17.2
    Uninstalling numpy-1.17.2:
      Successfully uninstalled numpy-1.17.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.3.1
    Uninstalling scipy-1.3.1:
      Successfully uninstalled scipy-1.3.1
  Attempting uninstall: statsmodels
    Found existing installation: statsmodels 0.10.1
    Uninstalling statsmodels-0.10.1:
      Successfully uninstalled statsmodels-0.10.1
  Attempting uninstall: scikit-learn
    Found existing

## Univariate statistical tests

Methods like F-test estimate linear dependency between two random variables (feature and target). These method assume that the variables follow a Gaussian Distribution. Features must be non negative.

There are mutual information based methods that can capture any kind of statistical dependency, but are non-parametric and thus, require more samples for accurate estimation.

The scoring function depends on task:

    For classification tasks: chi2, f_classif, mutual_info_classif
    For regression tasks: f_regression, mutual_info_regression

If you use sparse data (i.e. data represented as sparse matrices), chi2, mutual_info_regression, mutual_info_classif will deal with the data without making it dense.

In [145]:
from sklearn.feature_selection import SelectKBest, chi2, SelectPercentile, mutual_info_classif

# Input scoring function
X_new = SelectKBest(mutual_info_classif, k=100).fit_transform(X_train, y_train)

In [143]:
X_new = SelectPercentile(chi2, percentile=10).fit_transform(X_train, y_train)

ValueError: Input X must be non-negative.